services:
  postgres:
    image: postgres:16-alpine
    container_name: ${POSTGRES_CONTAINER_NAME:-jemputanku-postgres}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-jemputanku_db}
      POSTGRES_USER: ${POSTGRES_USER:-jemputanku_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - jemputanku_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-jemputanku_user} -d ${POSTGRES_DB:-jemputanku_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ${PGADMIN_CONTAINER_NAME:-jemputanku-pgadmin}
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@jemputanku.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin123}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - jemputanku_network

  # Mailpit for email testing
  mailpit:
    image: axllent/mailpit:latest
    container_name: ${MAILPIT_CONTAINER_NAME:-jemputanku-mailpit}
    restart: unless-stopped
    ports:
      - "${MAILPIT_WEB_PORT:-8025}:8025"    # Web interface
      - "${MAILPIT_SMTP_PORT:-1025}:1025"   # SMTP server
    environment:
      MP_MAX_MESSAGES: ${MAILPIT_MAX_MESSAGES:-5000}
      MP_DATABASE: ${MAILPIT_DATABASE:-/data/mailpit.db}
      MP_SMTP_AUTH_ACCEPT_ANY: ${MAILPIT_SMTP_AUTH:-1}
      MP_SMTP_AUTH_ALLOW_INSECURE: ${MAILPIT_SMTP_INSECURE:-1}
    volumes:
      - mailpit_data:/data
    networks:
      - jemputanku_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8025/api/v1/info"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  mailpit_data:
    driver: local

networks:
  jemputanku_network:
    driver: bridge